# Generated by Django 4.1 on 2022-08-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoviesDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, null=True)),
                ("release_year", models.DateField(null=True)),
                ("genres", models.CharField(max_length=300, null=True)),
                ("director", models.CharField(max_length=250, null=True)),
                ("actor", models.CharField(max_length=250, null=True)),
                ("language", models.CharField(max_length=250, null=True)),
                ("rating", models.IntegerField(default=0)),
            ],
        ),
    ]
