# Generated by Django 4.1 on 2022-08-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesdetails",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
